# Generated by Django 4.2.7 on 2024-03-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_Title', models.CharField(max_length=255)),
                ('room_type', models.CharField(choices=[('Ac', 'Complete-Ac'), ('Non-Ac', 'No-Ac'), ('Both', 'Ac+NonAc')], max_length=20)),
                ('room_capacity', models.TextField(max_length=255)),
                ('check_in', models.TextField(max_length=255)),
                ('check_out', models.TextField(max_length=255)),
                ('extra_services', models.TextField(max_length=255)),
                ('total_charge', models.TextField(max_length=255)),
            ],
        ),
    ]
